# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34872c17e7e916be13e0c20c133b167d8034705f25f8c96ba42bba9bca4b153fe9d17982615bf984fd8c93bdc0d470009555abb98bd3d24bd0a55f18523c027

test:
  secret_key_base: 5c6da1eb9734165158c3536793c2b8c0cdca99dd915163d8e8e76292421a54e3a900124a88e979507cfcd415721c271159f052a3f14b83d2e9e627213be30e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
